import { chromium } from "@playwright/test";
import fs from "node:fs";
const S = process.argv[2]; const size = process.argv[3] ?? "small";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ baseURL: `http://127.0.0.1:${process.env.PORTX || 3100}`, locale: "de-DE" });
page.on("console", m => console.log("console:", m.text()));
page.on("response", r => { if (r.request().method()==="POST") console.log("POST", r.url(), r.status()); });
// make a jpeg in-browser
await page.goto("/login");
const b64 = await page.evaluate(async (size) => {
  const [w,h] = size==="big" ? [4000,3000] : [1200,900];
  const c = document.createElement("canvas"); c.width=w; c.height=h; const x=c.getContext("2d");
  const img = x.createImageData(w,h); for (let i=0;i<img.data.length;i++) img.data[i]=Math.random()*255; x.putImageData(img,0,0);
  const blob = await new Promise(r=>c.toBlob(r,"image/jpeg",0.95));
  const buf = new Uint8Array(await blob.arrayBuffer()); let s=""; for (const b of buf) s+=String.fromCharCode(b); return btoa(s);
}, size);
fs.writeFileSync(`${S}/${size}.jpg`, Buffer.from(b64,"base64"));
console.log("image bytes", fs.statSync(`${S}/${size}.jpg`).size);
const id = Date.now().toString(36);
await page.goto("/register");
await page.getByLabel(/display name|anzeigename/i).fill("T "+id);
await page.getByLabel(/username|benutzername/i).fill("u"+id);
await page.getByLabel(/^email$|^e-mail$/i).fill(`u${id}@example.test`);
await page.getByLabel(/password|passwort/i).fill("a-long-enough-passphrase");
await page.getByRole("button", { name: /create account|konto erstellen/i }).click();
await page.waitForURL("**/onboarding");
await page.getByLabel(/date of birth|geburtsdatum/i).fill("1992-05-14");
await page.getByLabel(/height|körpergröße/i).fill("178");
await page.getByLabel(/current weight|aktuelles gewicht/i).fill("76.4");
await page.getByLabel(/biological sex|biologisches geschlecht/i).selectOption("FEMALE");
await page.getByRole("button", { name: /finish setup|einrichtung abschließen/i }).click();
await page.waitForURL(u => !u.pathname.includes("onboarding"));
await page.goto("/recipes/new");
await page.locator("#recipe-import-image").setInputFiles(`${S}/${size}.jpg`);
await page.waitForTimeout(1500);
if (process.env.TOUCH) { fs.appendFileSync(`${S}/${size}.jpg`, Buffer.from([0])); }
if (process.env.OFFLINE) await page.route("**/recipes/new", r => r.request().method()==="POST" ? r.abort("failed") : r.continue());
await page.locator("#recipe-import-heading").locator("xpath=ancestor::section").getByRole("button").last().click();
await page.waitForTimeout(6000);
console.log("URL", page.url());
console.log((await page.locator("main").innerText()).slice(0,400));
await browser.close();
