import type { FoodProvider, NormalizedFood } from "./food";
const fields="code,product_name,generic_name,brands,quantity,serving_size,countries,image_front_url,ingredients_text,allergens,nutriments,nutrition_grades,nova_group,last_modified_t,completeness";
export class OpenFoodFactsProvider implements FoodProvider {
  constructor(private baseUrl=process.env.OPENFOODFACTS_BASE_URL ?? "https://world.openfoodfacts.org", private userAgent=process.env.OPENFOODFACTS_USER_AGENT ?? "NutriCore/0.1") {}
  async request(path:string) { const response=await fetch(`${this.baseUrl}${path}`,{headers:{"User-Agent":this.userAgent},signal:AbortSignal.timeout(8000)}); if(!response.ok) throw new Error(`OFF unavailable (${response.status})`); return response.json(); }
  normalizeProduct(p:Record<string,unknown>):NormalizedFood { const n=(p.nutriments??{}) as Record<string,number|undefined>; return {externalId:String(p.code),barcode:String(p.code),name:String(p.product_name||p.generic_name||"Unknown product"),brand:p.brands?String(p.brands):undefined,basisAmount:100,basisUnit:"G",servingUnit:p.serving_size?String(p.serving_size):undefined,nutrients:{energyKcal:n["energy-kcal_100g"]??null,protein:n.proteins_100g??null,carbohydrate:n.carbohydrates_100g??null,fat:n.fat_100g??null,saturatedFat:n["saturated-fat_100g"]??null,sugar:n.sugars_100g??null,fiber:n.fiber_100g??null,salt:n.salt_100g??null,sodium:n.sodium_100g??null},provenance:{provider:"OPEN_FOOD_FACTS",retrievedAt:new Date(),providerUpdatedAt:p.last_modified_t?new Date(Number(p.last_modified_t)*1000):undefined,confidence:typeof p.completeness==="number"?p.completeness:undefined},raw:p}; }
  async getByBarcode(barcode:string){ if(!/^\d{8,14}$/.test(barcode)) return null; const data=await this.request(`/api/v2/product/${barcode}.json?fields=${fields}`); return data.status===1?this.normalizeProduct(data.product):null; }
  async search(query:string){ const params=new URLSearchParams({categories_tags_en:query,fields,page_size:"10",json:"1"}); const data=await this.request(`/api/v2/search?${params}`) as {products?:Record<string,unknown>[]}; return (data.products??[]).map((p)=>this.normalizeProduct(p)); }
}
