import { redirect } from "next/navigation";
import Link from "next/link";
import { prisma } from "@/lib/db";
import { getSessionUser } from "@/server/session";
import { AppShell } from "@/components/app-shell";
import { reviewAiProposalAction } from "@/server/meal-ai-actions";

export const dynamic="force-dynamic";
export default async function AiReviewPage({params}:{params:Promise<{id:string}>}){
 const user=await getSessionUser();if(!user)redirect("/login");const {id}=await params;
 const input=await prisma.mealInput.findFirst({where:{id,userId:user.id},include:{aiJobs:{include:{proposal:true},orderBy:{createdAt:"desc"},take:1}}});if(!input)redirect("/diary");const job=input.aiJobs[0];
 const proposal=job?.proposal; const data=proposal?.proposed as {components?:Array<{name:string;quantity?:number;unit?:string;estimatedGrams?:number;preparation?:string;canonicalFoodId?:string|null;sources?:Array<{title:string;url:string}>}>;warnings?:string[]} | undefined;
 return <AppShell displayName={user.displayName}><div className="page-head"><div><h1>AI enrichment</h1><p className="muted">Original input is preserved. AI suggestions remain unconfirmed until you approve them.</p></div><Link className="btn btn-quiet" href="/diary">Back to diary</Link></div>
 <section className="card"><h2>{input.text}</h2><p><span className={`ai-state ai-${job?.status.toLowerCase()}`}>{job?.status==="QUEUED"?"AI enrichment pending":job?.status==="RUNNING"?"AI enrichment in progress":job?.status==="COMPLETED"?"✓ Review AI enrichment":"AI enrichment failed"}</span></p>{job?.status==="QUEUED"||job?.status==="RUNNING"?<p className="muted">This page may be refreshed; you can continue using NutriCore while the worker runs.</p>:null}{job?.errorMessage?<div className="notice notice-warn">{job.errorMessage}</div>:null}</section>
 {proposal&&data?<section className="card" style={{marginTop:20}}><div className="card-head"><h2><span className="ai-badge">AI</span> Proposed components</h2><span className="muted">Confidence: {proposal.confidence}</span></div><div className="table-scroll"><table className="table"><thead><tr><th>Food</th><th>Quantity</th><th>Portion</th><th>Resolution</th></tr></thead><tbody>{data.components?.map((c,i)=><tr key={i}><td><strong>{c.name}</strong>{c.preparation?<><br/><span className="muted">{c.preparation}</span></>:null}</td><td>{c.quantity??"—"} {c.unit??""}</td><td>{c.estimatedGrams?`${c.estimatedGrams} g (estimated)`:"—"}</td><td>{c.canonicalFoodId?"Source verified":"Nutrition incomplete"}{c.sources?.[0]?.url?<><br/><a href={c.sources[0].url} rel="noreferrer" target="_blank">{c.sources[0].title}</a></>:null}</td></tr>)}</tbody></table></div><details><summary>Provenance</summary><pre className="provenance">{JSON.stringify(proposal.provenance,null,2)}</pre></details>{proposal.approvalStatus==="PENDING"?<form action={reviewAiProposalAction} className="button-row"><input type="hidden" name="proposalId" value={proposal.id}/><button className="btn btn-primary" name="decision" value="accept">✓ Accept all</button><button className="btn btn-quiet" name="decision" value="reject">Reject</button></form>:<p><strong>{proposal.approvalStatus==="ACCEPTED"?"✓ Approved":"Rejected"}</strong></p>}</section>:null}</AppShell>
}
